services:
  - type: web
    name: lucius-ai
    env: python
    buildCommand: ./render-build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --loop asyncio
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MONGO_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: STRIPE_SECRET_KEY
        sync: false
    disk:
      name: chroma-data
      mountPath: /opt/render/project/src/chroma_db
      sizeGB: 1
